
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/sbosch/.pico-sdk/cmake/v3.28.6/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:228 (message)"
      - "CMakeLists.txt:50 (project)"
    message: |
      The target system is: PICO -  - cortex-m0plus
      The host system is: Linux - 5.15.153.1-microsoft-standard-WSL2 - x86_64
...
